window.NOVACART_FALLBACK_CATALOG = [
  {
    id: "prod-1001",
    name: "Wireless Noise-Canceling Headphones",
    category: "Electronics",
    price: 5999,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
    description: "Over-ear headphones with rich sound, long battery life, and comfortable cushioning for daily use.",
    badge: "Best Seller",
    inventory: 24,
    featured: true
  },
  {
    id: "prod-1002",
    name: "Smart Fitness Watch",
    category: "Wearables",
    price: 3499,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    description: "Track workouts, heart rate, and notifications with a sleek all-day wearable design.",
    badge: "Top Rated",
    inventory: 38,
    featured: true
  },
  {
    id: "prod-1003",
    name: "Minimal Desk Lamp",
    category: "Home Office",
    price: 1499,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    description: "Modern desk lamp with adjustable brightness and a compact footprint for focused workspaces.",
    badge: "Fast Moving",
    inventory: 52,
    featured: true
  },
  {
    id: "prod-1004",
    name: "Portable Bluetooth Speaker",
    category: "Electronics",
    price: 2199,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=900&q=80",
    description: "Compact wireless speaker with deep bass, splash resistance, and easy travel portability.",
    badge: "Hot Deal",
    inventory: 31,
    featured: true
  },
  {
    id: "prod-1005",
    name: "Classic Leather Wallet",
    category: "Accessories",
    price: 999,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80",
    description: "Slim everyday wallet with multiple card slots, durable stitching, and premium texture.",
    badge: "Premium",
    inventory: 19,
    featured: true
  },
  {
    id: "prod-1006",
    name: "Ergonomic Office Chair",
    category: "Furniture",
    price: 8499,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=900&q=80",
    description: "Supportive office chair with breathable mesh, adjustable height, and comfortable lumbar support.",
    badge: "Workspace Pick",
    inventory: 16,
    featured: true
  },
  {
    id: "prod-1007",
    name: "Ceramic Coffee Mug Set",
    category: "Kitchen",
    price: 799,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?auto=format&fit=crop&w=900&q=80",
    description: "Set of stylish ceramic mugs designed for everyday tea, coffee, and gifting moments.",
    badge: "Home Favorite",
    inventory: 14,
    featured: true
  },
  {
    id: "prod-1008",
    name: "Canvas Travel Backpack",
    category: "Bags",
    price: 1899,
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    description: "Roomy backpack with laptop sleeve, travel-friendly pockets, and a clean modern silhouette.",
    inventory: 27,
    featured: false
  },
  {
    id: "prod-1009",
    name: "Compact Power Bank",
    category: "Electronics",
    price: 1299,
    rating: 4.1,
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=900&q=80",
    description: "Pocket-size charging backup with dual ports and enough power for busy days on the move.",
    inventory: 35,
    featured: false
  },
  {
    id: "prod-1010",
    name: "Premium Sneaker Pair",
    category: "Footwear",
    price: 4299,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    description: "Comfort-focused sneakers with a lightweight sole and versatile style for everyday wear.",
    badge: "Premium",
    inventory: 22,
    featured: true
  },
  {
    id: "prod-1011",
    name: "Stainless Water Bottle",
    category: "Lifestyle",
    price: 699,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80",
    description: "Insulated bottle that keeps drinks cool for hours and fits neatly in bags or cup holders.",
    inventory: 18,
    featured: false
  },
  {
    id: "prod-1012",
    name: "Wireless Keyboard and Mouse Combo",
    category: "Computer Accessories",
    price: 2499,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=900&q=80",
    description: "Clean desktop combo built for productivity, quiet typing, and clutter-free workstations.",
    badge: "Office Pick",
    inventory: 29,
    featured: true
  },
  {
    id: "prod-1013",
    name: "Decorative Table Clock",
    category: "Home Decor",
    price: 1599,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=900&q=80",
    description: "Compact statement clock that adds warmth and structure to desks, shelves, and side tables.",
    badge: "Gift Pick",
    inventory: 11,
    featured: true
  },
  {
    id: "prod-1014",
    name: "Skincare Essentials Kit",
    category: "Beauty",
    price: 1999,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80",
    description: "Daily skincare set with cleanser, moisturizer, and serum packed for easy self-care routines.",
    badge: "Gift Set",
    inventory: 9,
    featured: true
  },
  {
    id: "prod-1015",
    name: "Soft Throw Blanket",
    category: "Home Living",
    price: 1399,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    description: "Cozy blanket with a soft finish that works well for couches, reading nooks, and bedrooms.",
    inventory: 17,
    featured: false
  },
  {
    id: "prod-1016",
    name: "LED Ring Light",
    category: "Content Creator Gear",
    price: 2299,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    description: "Adjustable ring light with stand support for streaming, calls, tutorials, and content shoots.",
    badge: "Creator Pick",
    inventory: 13,
    featured: true
  },
  {
    id: "prod-1017",
    name: "Cotton Bedsheet Set",
    category: "Home Living",
    price: 1799,
    rating: 4.1,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    description: "Soft breathable bedsheet set designed for daily comfort with a neat and modern finish.",
    inventory: 33,
    featured: false
  },
  {
    id: "prod-1018",
    name: "Portable Mini Projector",
    category: "Electronics",
    price: 6499,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?auto=format&fit=crop&w=900&q=80",
    description: "Compact projector for movie nights, presentations, and flexible entertainment setups.",
    badge: "Seasonal",
    inventory: 8,
    featured: true
  },
  {
    id: "prod-1019",
    name: "Travel Trolley Bag",
    category: "Bags",
    price: 5499,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=900&q=80",
    description: "Durable hard-shell trolley with smooth wheels, secure storage, and sleek travel styling.",
    inventory: 26,
    featured: false
  },
  {
    id: "prod-1020",
    name: "Celebration Gift Box",
    category: "Gift Packs",
    price: 2899,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=900&q=80",
    description: "Curated gift box with premium lifestyle items, elegant packaging, and occasion-ready presentation.",
    badge: "Festive Pick",
    inventory: 7,
    featured: true
  }
];
